import Layout from "@/components/app/Layout";
import Button from "@/components/common/Button";
import Head from "next/head";

export default function Components() {
  return (
    <Layout>
      <Head>
        <title>Components</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="">
          <Button>Default Button</Button>
          <Button customClass="mr-10 ml-10" disabled>
            Disabled Button
          </Button>
          <Button customClass="mr-10" size="small">
            Small Button
          </Button>
          <Button customClass="mr-10" color="secondary">
            Secondary Button
          </Button>
          <Button customClass="mr-10" color="danger">
            Danger Button
          </Button>
          <Button variant="outlined" customClass="mr-10" size="small">
            Variant Button
          </Button>
          <Button size="large">Large Button</Button>
        </div>
      </main>
    </Layout>
  );
}
