import Layout from "@/components/app/Layout";
import Button from "@/components/common/Button";
import Head from "next/head";

export default function Components() {
  return (
    <Layout>
      <Head>
        <title>Components</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="">
          <Button>Default Button</Button>
          <Button size="small">Small Button</Button>
          <Button color="secondary">Secondary Button</Button>
          <Button color="danger">Danger Button</Button>
          <Button size="large">Large Button</Button>
        </div>
        <div>
          <button
            type="button"
            className="focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800"
          >
            Green
          </button>
          <button
            type="button"
            className="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900"
          >
            Red
          </button>
        </div>
      </main>
    </Layout>
  );
}
