import Layout from "@/components/app/Layout";
import Button from "@/components/common/Button";
import Headline from "@/components/common/Headline";
import Head from "next/head";

export default function Components() {
  return (
    <Layout>
      <Head>
        <title>Components</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="pb-40">
          <Button>Default Button</Button>
          <Button customClass="mr-10 ml-10" disabled>
            Disabled Button
          </Button>
          <Button customClass="mr-10" size="small">
            Small Button
          </Button>
          <Button customClass="mr-10" color="secondary">
            Secondary Button
          </Button>
          <Button customClass="mr-10" color="danger">
            Danger Button
          </Button>
          <Button customClass="mr-10" size="small">
            Variant Button
          </Button>
          <Button size="large">Large Button</Button>
        </div>

        <div>
          <Headline variant="h1">Title H1</Headline>
          <Headline variant="h2">Title H2</Headline>
          <Headline variant="h3">Title H3</Headline>
          <Headline variant="h4">Title H4</Headline>
          <Headline variant="h5">Title H5</Headline>
          <Headline variant="h6">Title H6</Headline>
          <Headline variant="h1" align="center">
            Title H1 + align center
          </Headline>
          <Headline variant="h2" align="center">
            Title H2 + align center
          </Headline>
          <Headline variant="h3" align="center">
            Title H3 + align center
          </Headline>
          <Headline variant="h4" align="center">
            Title H4 + align center
          </Headline>
          <Headline variant="h5" align="center">
            Title H5 + align center
          </Headline>
          <Headline variant="h6" align="center">
            Title H6 + align center
          </Headline>
        </div>
      </main>
    </Layout>
  );
}
