import Head from 'next/head'
import Layout from '@/components/app/Layout'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <h1
          className="text-center font-display text-4xl font-bold md:text-7xl md:leading-[5rem]"
        >
          Nextjs Starter Kit
        </h1>
        <p className="mt-6 text-center text-gray-500 md:text-xl">
        A template for site builders with NextJS, TypeScript, TailwindCSS
        </p>
      </div>
    </Layout>
  )
}
